name: test
on: [ push, pull_request ]

jobs:
  test:
    strategy:
      matrix:
        os:
        - windows-2022
        compiler:
        - cl

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1.9.0
        if: ${{ matrix.os == 'windows-2022' && matrix.compiler == 'cl' }}

      - run: |
          export OS=${{ matrix.os }}
          export COMPILER=${{ matrix.compiler }}
          ./test.sh
        shell: bash
