name: test
on: [ push, pull_request ]

jobs:
  test:
    strategy:
      matrix:
        os:
        - windows-2022
        - ubuntu-22.04
        compiler:
        - cl
        - g++
        - clang++
        exclude:
        # cl is Windows-only
        - os: ubuntu-22.04
          compiler: cl
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - if: ${{ matrix.os == 'windows-2022' && matrix.compiler == 'cl' }}
        uses: ilammy/msvc-dev-cmd@v1.9.0

      - if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libboost-dev libboost-thread-dev

      - run: |
          export OS=${{ matrix.os }}
          export COMPILER=${{ matrix.compiler }}
          ./test.sh
        shell: bash
